### PR TITLE
Create login feature

### PR DESCRIPTION
**Pull request by dingdongg**
## Description
- Implemented login feature and related security features
    - uses Redis as session storage
- Improve error logging
- refactor different modules into different routes

*This is a big PR so it can be kinda tricky to test. Let me know if you run into any trouble and/or to hop on a call to walk through it together*

## Testing

- before testing, run `npm install`
- you also have to install redis (see [this link](https://redis.io/docs/getting-started/installation/))
- if you want to see the state of the session storage throughout testing, open a new terminal and type `redis-cli`. 
    - the following are useful commands:
        - `keys *`: gets all sessions stored in memory at that moment
        - `get <session_id>`: retrieve a particular session
        - `flushall`: empties the session storage

__Flow #1:__
- try calling an endpoint that would typically require the user to be logged in
      - should get back 401 error, saying the user isn't authenticated
- call `GET /csrf-token` (this is the token to use whenever you make state-changing requests within this session)
- call `POST /login`, using a `x-csrf-token` header with value from the previous step
- user should now be authenticated (logged in)
- try calling an endpoint that would typically require the user to be logged in 
      - this time, the API call should be successful
- try calling `DELETE /users/:user_id` (create a test user to delete if you want)
      - if you are logged in to an admin account, the user should be deleted
      - otherwise, you should get back 403 error, saying the user isn't authorized to access this resource

__Flow #2:__
- call `GET /csrf-token`
- call `POST /login`, using a `x-csrf-token` header with value from the previous step
- call `POST /logout`, again using the CSRF token from step 1
- should be successfully logged out 
- in Redis, the login session should be destroyed

### CODE REVIEW

**Review by michaelt16 — COMMENTED** [review]
im kinda unfamiliar  on routers but next is unused, just in case pointing out but lmk
image

**Review by michaelt16 — COMMENTED** [review]
image
image
image
flow 2 is perfect. All functionalities worked as intended.

**Comment by dingdongg** [comment]
> image image image flow 2 is perfect. All functionalities worked as intended.

How about flow 1? Did everything go as expected?

**Review by michaelt16 — COMMENTED** [review]
image
before logged in 

image
after logged in , endpoint works 

trying to delete self 
image

ok now im trying to delete this user 
image

it says cannot delete 
image
i logged in to this one and it should be admin 
image

last bullet point for flow 1 does not work as expected, unless i made a mistake

**Comment by dingdongg** [comment]
> image before logged in
> 
> image after logged in , endpoint works
> 
> trying to delete self image
> 
> ok now im trying to delete this user image
> 
> it says cannot delete image i logged in to this one and it should be admin image
> 
> last bullet point for flow 1 does not work as expected, unless i made a mistake

I should handle the self-deleting thing, good catch. 

Also the delete user feature seems to be working for me? maybe we can go through this flow together later

**Comment by michaelt16** [comment]
lgtm 83d406e29f0c41bbba8b2e7a7f7f02350c57c83a

**Review by michaelt16 — APPROVED** [review]
lgtm 83d406e29f0c41bbba8b2e7a7f7f02350c57c83a

**Pull request merged**
